const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#000',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
  },
  card: {
    backgroundColor: '#000',
    padding: '20px',
    borderRadius: '12px',
    width: '100%',
    maxWidth: '360px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  logoCircle: {
    width: '200px',
    height: '200px',
    borderRadius: '50%',
    overflow: 'hidden',
    backgroundColor: '#fff',
    marginBottom: '50px',
  },
  titulo: {
    fontSize: '24px',
    fontWeight: 'bold',
    textAlign: 'center',
    margin: 0,
  },
  subtitulo: {
    color: '#ffb700',
    fontWeight: 'bold',
    fontSize: '16px',
    letterSpacing: '1px',
    marginBottom: '16px',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid #ccc',
    marginBottom: '20px',
    fontSize: '16px',
  },
  buttonsContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
    flexWrap: 'wrap',
    width: '100%',
    marginTop: '8px',
  },
  button: {
    backgroundColor: '#ffb700',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: '16px',
    padding: '10px 24px',
    borderRadius: '28px',
    border: 'none',
    whiteSpace: 'nowrap',
  },
  cancelButton: {
    backgroundColor: '#5daaff',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: '16px',
    padding: '10px 24px',
    borderRadius: '28px',
    border: 'none',
    whiteSpace: 'nowrap',
  },
  barberLine: {
    height: '2px',
    backgroundColor: '#ffb700',
    width: '100%',
    marginTop: '12px',
  },
};

export default styles;
