const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#000',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '32px 16px',
  },
  logoCircle: {
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    backgroundColor: '#000',
    overflow: 'hidden',
    marginBottom: '12px',
  },
  logoImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '50%',
  },
  titulo: {
    fontSize: '24px',
    fontWeight: 'bold',
    textAlign: 'center',
    margin: 0,
  },
  subtitulo: {
    color: '#ffb700',
    fontWeight: 'bold',
    fontSize: '16px',
    letterSpacing: '1px',
    marginBottom: '16px',
  },
  lista: {
    width: '100%',
    maxWidth: '400px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '24px',
  },
  barbeiroCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    borderRadius: '12px',
    backgroundColor: '#ffe97f',
    border: 'none',
    cursor: 'pointer',
    transition: '0.2s',
  },
  cardContent: { 
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
  },
    servicoCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '12px 16px',
    borderRadius: '12px',
    backgroundColor: '#FFE97F',
    border: 'none',
    cursor: 'pointer',
    transition: '0.2s',
    color: '#000',
    gap: '4px',
  },
  servicoTitulo: {
    fontWeight: 'bold',
    fontSize: '15px',
    margin: 0,
    color: '#000',
  },
  servicoDetalhe: {
    margin: 0,
    fontSize: '13px',
    color: '#444',
  },
  avatar: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    boxShadow: '0 0 10px #ffb700',
  },
  nome: {
    fontWeight: 'bold',
    color: '#000',
    fontSize: '15px',
  },
  botaoVoltar: {
    backgroundColor: '#5daaff',
    color: '#fff',
    fontSize: '18px',
    fontWeight: 'bold',
    padding: '10px 28px',
    borderRadius: '28px',
    border: 'none',
    cursor: 'pointer',
  },
};

export default styles;
