const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#000',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '32px 16px',
  },
  logoCircle: {
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    backgroundColor: '#000',
    overflow: 'hidden',
    marginBottom: '12px',
  },
  logoImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '50%',
  },
  titulo: {
    fontSize: '24px',
    fontWeight: 'bold',
    textAlign: 'center',
    margin: '0 0 4px 0',
  },
  versao: {
    fontSize: '10px',
    color: '#ccc',
    marginBottom: '10px',
  },
  subtitulo: {
    color: '#ffb700',
    fontWeight: 'bold',
    fontSize: '16px',
    letterSpacing: '1px',
    marginBottom: '16px',
  },
  calendarioWrapper: {
    backgroundColor: '#fff',
    borderRadius: '8px',
    padding: '10px',
    color: '#000',
  },
  horariosWrapper: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '10px',
    margin: '20px 0',
  },
  horarioBtn: {
    backgroundColor: '#ffe97f',
    color: '#000',
    fontWeight: 'bold',
    padding: '10px 16px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  botaoVoltar: {
    backgroundColor: '#5daaff',
    color: '#fff',
    fontSize: '18px',
    fontWeight: 'bold',
    padding: '10px 28px',
    borderRadius: '28px',
    border: 'none',
    cursor: 'pointer',
  },

  // ✅ ESTILOS PARA TELA DE CONFIRMAÇÃO
  statusConfirmado: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#2ed573',
    padding: '10px 20px',
    borderRadius: '25px',
    marginBottom: '24px',
    animation: 'pulse 2s infinite',
  },
  checkIcon: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#fff',
  },
  statusTexto: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#fff',
  },

  // Card de Resumo
  resumoCard: {
    width: '100%',
    maxWidth: '370px',
    backgroundColor: '#fff',
    color: '#000',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '24px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.3)',
  },
  resumoItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '12px',
    marginBottom: '10px',
    borderBottom: '1px solid #eee',
  },
  resumoItemServicos: {
    paddingBottom: '12px',
    marginBottom: '12px',
    borderBottom: '1px solid #eee',
  },
  resumoLabel: {
    fontSize: '14x',
    fontWeight: '500',
    color: '#666',
  },
  resumoValor: {
    fontSize: '15px',
    color: '#000',
  },
  resumoValorDestaque: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#ff7a00',
  },
  // ✅ NOVO ESTILO PARA HORÁRIO SIMPLIFICADO
  horarioSimples: {
    textAlign: 'right',
  },
  dataSimples: {
    fontSize: '15px',
    color: '#000',
  },
  servicosLista: {
    marginTop: '8px',
  },
  servicoItem: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    padding: '2px 0',
    color: '#444',
  },
  valorTotal: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#2ed573',
  },

  // Lembretes
  lembretesTitulo: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#ffb700',
    textAlign: 'center',
    marginBottom: '16px',
    marginTop: '0px',
  },
  lembretesContainer: {
    width: '100%',
    maxWidth: '400px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '24px',
  },
  lembreteBtn: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    transition: 'all 0.3s ease',
    position: 'relative',
  },
  lembreteIcon: {
    fontSize: '16px',
  },
  checkMark: {
    position: 'absolute',
    right: '16px',
    fontSize: '14px',
    fontWeight: 'bold',
  },

  // Botões de Ação
  botoesContainer: {
    width: '100%',
    maxWidth: '400px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '24px',
  },
  botaoCompartilhar: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    backgroundColor: '#333',
    color: '#fff',
    border: '1px solid #555',
    padding: '12px 16px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  compartilharIcon: {
    fontSize: '16px',
  },
  botaoAgendar: {
    width: '100%',
    backgroundColor: '#ffc132',
    color: '#000',
    fontWeight: 'bold',
    padding: '16px',
    border: 'none',
    borderRadius: '28px',
    fontSize: '16px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },

  // Footer
  footer: {
    textAlign: 'center',
    color: '#666',
    fontSize: '12px',
    lineHeight: '1.4',
  },
};

export default styles;