const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#000',
    color: '#fff',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '24px',
  },
  card: {
    width: '100%',
    maxWidth: '360px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    height: '520px',
    gap: '24px',
  },
  logoCircle: {
    width: '250px',
    height: '250px',
    backgroundColor: '#000',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    border: 'none',
    boxShadow: 'none',
  },
  iconGroup: {
    display: 'flex',
    gap: '8px',
    marginBottom: '8px',
    fontSize: '20px',
  },
  title: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: '20px',
    letterSpacing: '1px',
    marginTop: '24px',
  },
  barberLine: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '4px',
  },
  line: {
    height: '1px',
    width: '32px',
    backgroundColor: '#ff7a00',
  },
  barberText: {
    color: '#ff7a00',
    fontWeight: 'bold',
    fontSize: '12px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  input: {
    height: '48px',
    padding: '0 12px',
    borderRadius: '6px',
    fontSize: '16px',
    border: 'none',
    color: '#000',
  },
  button: {
    backgroundColor: '#ff7a00',
    color: '#fff',
    fontWeight: 'bold',
    padding: '16px',
    border: 'none',
    borderRadius: '999px',
    fontSize: '16px',
    transition: '0.3s',
  },
  cancelButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#fff',
    textDecoration: 'underline',
    fontSize: '14px',
    cursor: 'pointer',
  },
  identificar: {
    color: '#f2883a',
    fontWeight: 'bold',
    display: 'flex',
    justifyContent: 'space-between',
    height: '24px',
  },
};

export default styles;
